In [1]:
import warnings
warnings.filterwarnings("ignore")
from __future__ import print_function

In [2]:

import pyLDAvis
import pyLDAvis.sklearn

pyLDAvis.enable_notebook()

# Create a topic modeling visualization

In [3]:
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
newsgroups = fetch_20newsgroups(categories=['sci.med','sci.space','talk.politics.guns'],remove=('headers', 'footers', 'quotes'))
docs_raw = newsgroups.data
print(len(docs_raw))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


1733


In [4]:
#Term Frequency 
tf_vectorizer = CountVectorizer(strip_accents = 'unicode',
                                stop_words = 'english',
                                lowercase = True,
                                token_pattern = r'\b[a-zA-Z]{3,}\b',
                                max_df = 0.5, 
                                min_df = 10)
dtm_tf = tf_vectorizer.fit_transform(docs_raw)
print(dtm_tf.shape)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


(1733, 2589)


In [5]:
# Term Frequency Inverse Doc Frequency (Bag of words)
tfidf_vectorizer = TfidfVectorizer(**tf_vectorizer.get_params())
dtm_tfidf = tfidf_vectorizer.fit_transform(docs_raw)
print(dtm_tfidf.shape)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


(1733, 2589)


In [6]:
# for TF DTM
lda_tf = LatentDirichletAllocation(n_components=3, random_state=0)
lda_tf.fit(dtm_tf)
# for TFIDF DTM
lda_tfidf = LatentDirichletAllocation(n_components=3, random_state=0)
lda_tfidf.fit(dtm_tfidf)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


LatentDirichletAllocation(n_components=3, random_state=0)

In [7]:
pyLDAvis.sklearn.prepare(lda_tf, dtm_tf, tf_vectorizer)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic                                                
1      0.145987 -0.073183       1        1  46.622924
0     -0.155903 -0.060055       2        1  28.575160
2      0.009915  0.133239       3        1  24.801917, topic_info=          Term         Freq        Total Category  logprob  loglift
2182     space  1000.000000  1000.000000  Default  30.0000  30.0000
1513      nasa   394.000000   394.000000  Default  29.0000  29.0000
1021       gun   603.000000   603.000000  Default  28.0000  28.0000
1276    launch   272.000000   272.000000  Default  27.0000  27.0000
720        edu   529.000000   529.000000  Default  26.0000  26.0000
...        ...          ...          ...      ...      ...      ...
570        day    91.398365   234.522035   Topic3  -5.7641   0.4519
2523     water    81.802849   133.673097   Topic3  -5.8751   0.9032
2562      work    81.683391   228.480976   Topic3  -5.8765   0.3656
2164  software    79.850975   126.207865   Topic3  -5.8992   0.9365
1677    people    81.609549   735.235405   Topic3  -5.8774  -0.8040

[221 rows x 6 columns], token_table=      Topic      Freq       Term
term                            
44        2  0.977791  aerospace
60        3  0.996787       aids
67        2  0.975579      allen
79        1  0.989471  amendment
83        1  0.016143       ames
...     ...       ...        ...
2581      3  0.168592       year
2582      1  0.375525      years
2582      2  0.231323      years
2582      3  0.390546      years
2583      3  0.989526      yeast

[350 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[2, 1, 3])

In [8]:
pyLDAvis.sklearn.prepare(lda_tfidf, dtm_tfidf, tfidf_vectorizer)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic                                                
2     -0.066771 -0.029092       1        1  55.269740
1      0.074723 -0.020698       2        1  38.279381
0     -0.007951  0.049790       3        1   6.450879, topic_info=         Term       Freq      Total Category  logprob  loglift
1021      gun  21.000000  21.000000  Default  30.0000  30.0000
2182    space  30.000000  30.000000  Default  29.0000  29.0000
1022     guns  14.000000  14.000000  Default  28.0000  28.0000
412       com  14.000000  14.000000  Default  27.0000  27.0000
1568   object   3.000000   3.000000  Default  26.0000  26.0000
...       ...        ...        ...      ...      ...      ...
2064   search   0.849052   3.742789   Topic3  -6.4923   1.2575
2564  working   0.872830   5.628340   Topic3  -6.4647   0.8771
1861    quite   0.825225   9.769242   Topic3  -6.5208   0.2696
2316  talking   0.771582   6.388205   Topic3  -6.5880   0.6272
720       edu   0.774839  21.702173   Topic3  -6.5838  -0.5916

[174 rows x 6 columns], token_table=      Topic      Freq       Term
term                            
37        1  0.449743      adult
37        3  0.449743      adult
79        2  0.964695  amendment
136       1  0.414835    arizona
136       3  0.414835    arizona
...     ...       ...        ...
2580      2  0.849784       yeah
2581      1  0.459707       year
2581      2  0.536325       year
2582      1  0.764803      years
2582      2  0.278110      years

[222 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[3, 2, 1])

## Additional Parameters

In [45]:
# for TF DTM
lda_tf = LatentDirichletAllocation(n_components=10, random_state=0,learning_method = 'online',learning_decay=0.5)
lda_tf.fit(dtm_tf)
# for TFIDF DTM
lda_tfidf = LatentDirichletAllocation(n_components=10, random_state=0,learning_method = 'online',learning_decay=0.6)
lda_tfidf.fit(dtm_tfidf)


LatentDirichletAllocation(learning_decay=0.6, learning_method='online',
                          random_state=0)

In [46]:
pyLDAvis.sklearn.prepare(lda_tf, dtm_tf, tf_vectorizer)

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic                                                
3      0.135369  0.087708       1        1  23.028645
4      0.039982 -0.223813       2        1  18.405478
2      0.082383  0.009094       3        1  12.938279
5      0.167290  0.052986       4        1  11.204640
6      0.080953 -0.181634       5        1  10.869215
8     -0.202368 -0.092991       6        1   8.171436
1     -0.147775  0.055778       7        1   7.203018
9      0.084170 -0.070562       8        1   3.072936
0      0.043381  0.307623       9        1   2.713385
7     -0.283385  0.055809      10        1   2.392968, topic_info=         Term        Freq       Total Category  logprob  loglift
720       edu  548.000000  548.000000  Default  30.0000  30.0000
2182    space  976.000000  976.000000  Default  29.0000  29.0000
1021      gun  654.000000  654.000000  Default  28.0000  28.0000
412       com  306.000000  306.000000  Default  27.0000  27.0000
883      file  313.000000  313.000000  Default  26.0000  26.0000
...       ...         ...         ...      ...      ...      ...
1414    means   26.972899  102.204606  Topic10  -4.6462   2.4005
1691   person   29.835529  146.445817  Topic10  -4.5453   2.1417
2527  weapons   29.289238  180.975718  Topic10  -4.5638   1.9115
2460      use   34.588661  522.647521  Topic10  -4.3975   1.0173
2503     vote   22.080211   56.263699  Topic10  -4.8463   2.7973

[601 rows x 6 columns], token_table=      Topic      Freq       Term
term                            
0         7  0.965649    abiding
8         1  0.137708   accepted
8         5  0.849198   accepted
12        7  0.957132  accidents
19        1  0.281340     action
...     ...       ...        ...
2582      8  0.002884      years
2583      3  0.981978      yeast
2584      1  0.946193        yes
2584      3  0.039425        yes
2584      8  0.009856        yes

[1197 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[4, 5, 3, 6, 7, 9, 2, 10, 1, 8])

In [47]:
pyLDAvis.sklearn.prepare(lda_tfidf, dtm_tfidf, tfidf_vectorizer)

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic                                                
3      0.041001  0.050621       1        1  64.065445
8     -0.198920 -0.024808       2        1  19.293275
7      0.082574 -0.147589       3        1   3.504775
4      0.060417  0.084085       4        1   3.461419
1      0.005282  0.007082       5        1   1.712758
0      0.002175  0.006657       6        1   1.605738
6      0.001577  0.006049       7        1   1.591585
5      0.002055  0.005774       8        1   1.591498
2      0.002089  0.006192       9        1   1.591431
9      0.001749  0.005937      10        1   1.582077, topic_info=           Term       Freq      Total Category  logprob  loglift
720         edu  20.000000  20.000000  Default   30.000  30.0000
2172       soon  10.000000  10.000000  Default   29.000  29.0000
1513       nasa  14.000000  14.000000  Default   28.000  28.0000
994      gordon   9.000000   9.000000  Default   27.000  27.0000
2298  surrender   9.000000   9.000000  Default   26.000  26.0000
...         ...        ...        ...      ...      ...      ...
696        drug   0.053088   5.414827  Topic10   -7.859  -0.4785
891      finger   0.053088   1.924966  Topic10   -7.859   0.5557
816     explain   0.053088   3.855868  Topic10   -7.859  -0.1390
654     disease   0.053088  11.416446  Topic10   -7.859  -1.2244
1738   politics   0.053088   4.274494  Topic10   -7.859  -0.2420

[566 rows x 6 columns], token_table=      Topic      Freq         Term
term                              
24        1  0.904126       actual
37        1  0.466164        adult
43        1  0.942676  aeronautics
49        2  0.422988       afraid
49        3  0.422988       afraid
...     ...       ...          ...
2572      1  0.510927    worthless
2575      2  0.851988        write
2580      1  0.846819         yeah
2582      1  0.911144        years
2582      2  0.065082        years

[467 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[4, 9, 8, 5, 2, 1, 7, 6, 3, 10])

## Association rule mining

In [48]:
import pandas as pd
df = pd.read_csv('ratings_small.csv')
df.head(3)

userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182

In [50]:
#Select only movies with ratings larger than 3
df = df[df['rating']>3]
df.head(3)

userId  movieId  rating   timestamp
4        1     1172     4.0  1260759205
8        1     1339     3.5  1260759125
12       1     1953     4.0  1260759191

In [81]:
users = df['userId'].unique()

In [85]:
import numpy as np
dataset=[]
for i, row in enumerate(users):
    dataset.append(np.append(row,df[df['userId']==1].movieId.iloc[:].values))

In [84]:
dataset

[array([   1, 1172, 1339, 1953, 2105]),
 array([   2, 1172, 1339, 1953, 2105]),
 array([   3, 1172, 1339, 1953, 2105]),
 array([   4, 1172, 1339, 1953, 2105]),
 array([   5, 1172, 1339, 1953, 2105]),
 array([   6, 1172, 1339, 1953, 2105]),
 array([   7, 1172, 1339, 1953, 2105]),
 array([   8, 1172, 1339, 1953, 2105]),
 array([   9, 1172, 1339, 1953, 2105]),
 array([  10, 1172, 1339, 1953, 2105]),
 array([  11, 1172, 1339, 1953, 2105]),
 array([  12, 1172, 1339, 1953, 2105]),
 array([  13, 1172, 1339, 1953, 2105]),
 array([  14, 1172, 1339, 1953, 2105]),
 array([  15, 1172, 1339, 1953, 2105]),
 array([  16, 1172, 1339, 1953, 2105]),
 array([  17, 1172, 1339, 1953, 2105]),
 array([  18, 1172, 1339, 1953, 2105]),
 array([  19, 1172, 1339, 1953, 2105]),
 array([  20, 1172, 1339, 1953, 2105]),
 array([  21, 1172, 1339, 1953, 2105]),
 array([  22, 1172, 1339, 1953, 2105]),
 array([  23, 1172, 1339, 1953, 2105]),
 array([  24, 1172, 1339, 1953, 2105]),
 array([  25, 1172, 1339, 1953, 2105]),


# Apriori Algorithm to find Frequent sets

In [89]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)

frequent_itemsets = apriori(df, min_support=0.15, use_colnames=True)


frequent_itemsets

support                  itemsets
0       1.0                    (1172)
1       1.0                    (1339)
2       1.0                    (1953)
3       1.0                    (2105)
4       1.0              (1339, 1172)
5       1.0              (1953, 1172)
6       1.0              (2105, 1172)
7       1.0              (1953, 1339)
8       1.0              (2105, 1339)
9       1.0              (1953, 2105)
10      1.0        (1953, 1339, 1172)
11      1.0        (2105, 1339, 1172)
12      1.0        (1953, 1172, 2105)
13      1.0        (1953, 1339, 2105)
14      1.0  (1953, 1339, 1172, 2105)

In [113]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth
import time

start = time.time()
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)

frequent_itemsets_1 = apriori(df, min_support=0.01, use_colnames=True)

end = time.time()
print('Time to compute: %0.3f sec'%(end-start))
frequent_itemsets_1

Time to compute: 0.019 sec


support                  itemsets
0       1.0                    (1172)
1       1.0                    (1339)
2       1.0                    (1953)
3       1.0                    (2105)
4       1.0              (1339, 1172)
5       1.0              (1953, 1172)
6       1.0              (2105, 1172)
7       1.0              (1953, 1339)
8       1.0              (2105, 1339)
9       1.0              (1953, 2105)
10      1.0        (1953, 1339, 1172)
11      1.0        (2105, 1339, 1172)
12      1.0        (1953, 1172, 2105)
13      1.0        (1953, 1339, 2105)
14      1.0  (1953, 1339, 1172, 2105)

In [112]:
start = time.time()
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)

frequent_itemsets_2 = apriori(df, min_support=0.001, use_colnames=True)

end = time.time()
timer = end-start
print('Time to compute: %0.3f sec'%timer)
frequent_itemsets_2

Time to compute: 0.962 sec


support                       itemsets
0      0.00149                            (1)
1      0.00149                            (2)
2      0.00149                            (3)
3      0.00149                            (4)
4      0.00149                            (5)
...        ...                            ...
10746  0.00149  (1953, 1172, 2105, 1339, 667)
10747  0.00149  (1953, 1172, 2105, 1339, 668)
10748  0.00149  (1953, 1172, 2105, 1339, 669)
10749  0.00149  (1953, 1172, 2105, 1339, 670)
10750  0.00149  (1953, 1172, 2105, 1339, 671)

[10751 rows x 2 columns]

## Experiment with different confidence_level thresholds when mining for rules

In [90]:
from mlxtend.frequent_patterns import association_rules

association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)

antecedents         consequents  antecedent support  \
0               (1339)              (1172)                 1.0   
1               (1172)              (1339)                 1.0   
2               (1953)              (1172)                 1.0   
3               (1172)              (1953)                 1.0   
4               (2105)              (1172)                 1.0   
5               (1172)              (2105)                 1.0   
6               (1953)              (1339)                 1.0   
7               (1339)              (1953)                 1.0   
8               (2105)              (1339)                 1.0   
9               (1339)              (2105)                 1.0   
10              (1953)              (2105)                 1.0   
11              (2105)              (1953)                 1.0   
12        (1953, 1339)              (1172)                 1.0   
13        (1953, 1172)              (1339)                 1.0   
14        (1339, 1172)              (1953)                 1.0   
15              (1953)        (1339, 1172)                 1.0   
16              (1339)        (1953, 1172)                 1.0   
17              (1172)        (1953, 1339)                 1.0   
18        (2105, 1339)              (1172)                 1.0   
19        (2105, 1172)              (1339)                 1.0   
20        (1339, 1172)              (2105)                 1.0   
21              (2105)        (1339, 1172)                 1.0   
22              (1339)        (2105, 1172)                 1.0   
23              (1172)        (2105, 1339)                 1.0   
24        (1953, 1172)              (2105)                 1.0   
25        (1953, 2105)              (1172)                 1.0   
26        (2105, 1172)              (1953)                 1.0   
27              (1953)        (2105, 1172)                 1.0   
28              (1172)        (1953, 2105)                 1.0   
29              (2105)        (1953, 1172)                 1.0   
30        (1953, 1339)              (2105)                 1.0   
31        (1953, 2105)              (1339)                 1.0   
32        (2105, 1339)              (1953)                 1.0   
33              (1953)        (2105, 1339)                 1.0   
34              (1339)        (1953, 2105)                 1.0   
35              (2105)        (1953, 1339)                 1.0   
36  (1953, 1339, 1172)              (2105)                 1.0   
37  (1953, 1339, 2105)              (1172)                 1.0   
38  (1953, 1172, 2105)              (1339)                 1.0   
39  (2105, 1339, 1172)              (1953)                 1.0   
40        (1953, 1339)        (2105, 1172)                 1.0   
41        (1953, 1172)        (2105, 1339)                 1.0   
42        (1953, 2105)        (1339, 1172)                 1.0   
43        (1339, 1172)        (1953, 2105)                 1.0   
44        (2105, 1339)        (1953, 1172)                 1.0   
45        (2105, 1172)        (1953, 1339)                 1.0   
46              (1953)  (2105, 1339, 1172)                 1.0   
47              (1339)  (1953, 1172, 2105)                 1.0   
48              (1172)  (1953, 1339, 2105)                 1.0   
49              (2105)  (1953, 1339, 1172)                 1.0   

    consequent support  support  confidence  lift  leverage  conviction  
0                  1.0      1.0         1.0   1.0       0.0         inf  
1                  1.0      1.0         1.0   1.0       0.0         inf  
2                  1.0      1.0         1.0   1.0       0.0         inf  
3                  1.0      1.0         1.0   1.0       0.0         inf  
4                  1.0      1.0         1.0   1.0       0.0         inf  
5                  1.0      1.0         1.0   1.0       0.0         inf  
6                  1.0      1.0         1.0   1.0       0.0         inf  
7                  1.0      1.0         1.0   1.0   

## Rules discovered for confidence level threshold 0.8

In [91]:
from mlxtend.frequent_patterns import association_rules

association_rules(frequent_itemsets, metric="confidence", min_threshold=0.8)

antecedents         consequents  antecedent support  \
0               (1339)              (1172)                 1.0   
1               (1172)              (1339)                 1.0   
2               (1953)              (1172)                 1.0   
3               (1172)              (1953)                 1.0   
4               (2105)              (1172)                 1.0   
5               (1172)              (2105)                 1.0   
6               (1953)              (1339)                 1.0   
7               (1339)              (1953)                 1.0   
8               (2105)              (1339)                 1.0   
9               (1339)              (2105)                 1.0   
10              (1953)              (2105)                 1.0   
11              (2105)              (1953)                 1.0   
12        (1953, 1339)              (1172)                 1.0   
13        (1953, 1172)              (1339)                 1.0   
14        (1339, 1172)              (1953)                 1.0   
15              (1953)        (1339, 1172)                 1.0   
16              (1339)        (1953, 1172)                 1.0   
17              (1172)        (1953, 1339)                 1.0   
18        (2105, 1339)              (1172)                 1.0   
19        (2105, 1172)              (1339)                 1.0   
20        (1339, 1172)              (2105)                 1.0   
21              (2105)        (1339, 1172)                 1.0   
22              (1339)        (2105, 1172)                 1.0   
23              (1172)        (2105, 1339)                 1.0   
24        (1953, 1172)              (2105)                 1.0   
25        (1953, 2105)              (1172)                 1.0   
26        (2105, 1172)              (1953)                 1.0   
27              (1953)        (2105, 1172)                 1.0   
28              (1172)        (1953, 2105)                 1.0   
29              (2105)        (1953, 1172)                 1.0   
30        (1953, 1339)              (2105)                 1.0   
31        (1953, 2105)              (1339)                 1.0   
32        (2105, 1339)              (1953)                 1.0   
33              (1953)        (2105, 1339)                 1.0   
34              (1339)        (1953, 2105)                 1.0   
35              (2105)        (1953, 1339)                 1.0   
36  (1953, 1339, 1172)              (2105)                 1.0   
37  (1953, 1339, 2105)              (1172)                 1.0   
38  (1953, 1172, 2105)              (1339)                 1.0   
39  (2105, 1339, 1172)              (1953)                 1.0   
40        (1953, 1339)        (2105, 1172)                 1.0   
41        (1953, 1172)        (2105, 1339)                 1.0   
42        (1953, 2105)        (1339, 1172)                 1.0   
43        (1339, 1172)        (1953, 2105)                 1.0   
44        (2105, 1339)        (1953, 1172)                 1.0   
45        (2105, 1172)        (1953, 1339)                 1.0   
46              (1953)  (2105, 1339, 1172)                 1.0   
47              (1339)  (1953, 1172, 2105)                 1.0   
48              (1172)  (1953, 1339, 2105)                 1.0   
49              (2105)  (1953, 1339, 1172)                 1.0   

    consequent support  support  confidence  lift  leverage  conviction  
0                  1.0      1.0         1.0   1.0       0.0         inf  
1                  1.0      1.0         1.0   1.0       0.0         inf  
2                  1.0      1.0         1.0   1.0       0.0         inf  
3                  1.0      1.0         1.0   1.0       0.0         inf  
4                  1.0      1.0         1.0   1.0       0.0         inf  
5                  1.0      1.0         1.0   1.0       0.0         inf  
6                  1.0      1.0         1.0   1.0       0.0         inf  
7                  1.0      1.0         1.0   1.0   

## Rules discovered for condfidence level threshold 0.9

In [92]:
from mlxtend.frequent_patterns import association_rules

association_rules(frequent_itemsets, metric="confidence", min_threshold=0.9)


antecedents         consequents  antecedent support  \
0               (1339)              (1172)                 1.0   
1               (1172)              (1339)                 1.0   
2               (1953)              (1172)                 1.0   
3               (1172)              (1953)                 1.0   
4               (2105)              (1172)                 1.0   
5               (1172)              (2105)                 1.0   
6               (1953)              (1339)                 1.0   
7               (1339)              (1953)                 1.0   
8               (2105)              (1339)                 1.0   
9               (1339)              (2105)                 1.0   
10              (1953)              (2105)                 1.0   
11              (2105)              (1953)                 1.0   
12        (1953, 1339)              (1172)                 1.0   
13        (1953, 1172)              (1339)                 1.0   
14        (1339, 1172)              (1953)                 1.0   
15              (1953)        (1339, 1172)                 1.0   
16              (1339)        (1953, 1172)                 1.0   
17              (1172)        (1953, 1339)                 1.0   
18        (2105, 1339)              (1172)                 1.0   
19        (2105, 1172)              (1339)                 1.0   
20        (1339, 1172)              (2105)                 1.0   
21              (2105)        (1339, 1172)                 1.0   
22              (1339)        (2105, 1172)                 1.0   
23              (1172)        (2105, 1339)                 1.0   
24        (1953, 1172)              (2105)                 1.0   
25        (1953, 2105)              (1172)                 1.0   
26        (2105, 1172)              (1953)                 1.0   
27              (1953)        (2105, 1172)                 1.0   
28              (1172)        (1953, 2105)                 1.0   
29              (2105)        (1953, 1172)                 1.0   
30        (1953, 1339)              (2105)                 1.0   
31        (1953, 2105)              (1339)                 1.0   
32        (2105, 1339)              (1953)                 1.0   
33              (1953)        (2105, 1339)                 1.0   
34              (1339)        (1953, 2105)                 1.0   
35              (2105)        (1953, 1339)                 1.0   
36  (1953, 1339, 1172)              (2105)                 1.0   
37  (1953, 1339, 2105)              (1172)                 1.0   
38  (1953, 1172, 2105)              (1339)                 1.0   
39  (2105, 1339, 1172)              (1953)                 1.0   
40        (1953, 1339)        (2105, 1172)                 1.0   
41        (1953, 1172)        (2105, 1339)                 1.0   
42        (1953, 2105)        (1339, 1172)                 1.0   
43        (1339, 1172)        (1953, 2105)                 1.0   
44        (2105, 1339)        (1953, 1172)                 1.0   
45        (2105, 1172)        (1953, 1339)                 1.0   
46              (1953)  (2105, 1339, 1172)                 1.0   
47              (1339)  (1953, 1172, 2105)                 1.0   
48              (1172)  (1953, 1339, 2105)                 1.0   
49              (2105)  (1953, 1339, 1172)                 1.0   

    consequent support  support  confidence  lift  leverage  conviction  
0                  1.0      1.0         1.0   1.0       0.0         inf  
1                  1.0      1.0         1.0   1.0       0.0         inf  
2                  1.0      1.0         1.0   1.0       0.0         inf  
3                  1.0      1.0         1.0   1.0       0.0         inf  
4                  1.0      1.0         1.0   1.0       0.0         inf  
5                  1.0      1.0         1.0   1.0       0.0         inf  
6                  1.0      1.0         1.0   1.0       0.0         inf  
7                  1.0      1.0         1.0   1.0   